### ISSUE TITLE
maven仓库地址有吗

### ISSUE THREAD

**Issue by ITzhangqiang** [huaban/jieba-analysis#112]

**Comment by tripperGo** [comment]
为什么不去搜搜看？
`<dependency>
    <groupId>com.huaban</groupId>
    <artifactId>jieba-analysis</artifactId>
    <version>1.0.2</version>
</dependency>`

`compile group: 'com.huaban', name: 'jieba-analysis', version: '1.0.2'`

**Comment by ITzhangqiang** [comment]
thx
