### ISSUE TITLE
java版结巴 自定义添加词典

### ISSUE THREAD

**Issue by myccc456** [huaban/jieba-analysis#12]
WordDictionary dictAdd = WordDictionary.getInstance();
		
		File file = new File("D:/jieba-analysis/conf/user.dict");
		dictAdd.loadUserDict(file);

**Comment by piaolingxue** [comment]
@myccc456 请问什么问题?

**Comment by michaelliu03** [comment]
加载用户词典后分词阶段时没有什么效果呀
