### ISSUE TITLE
请问一下没有发布的词性标注版本，执行效率大概是多少？

### ISSUE THREAD

**Issue by yanbosan** [huaban/jieba-analysis#13]
请问一下没有发布的词性标注版本，执行效率大概是多少？是不是按照python版本的词性标注实现的？

**Comment by piaolingxue** [comment]
其实不加搜狗那个词典，性能差距可以忽略，但是引入搜狗词典后，发现分词性能突然变慢了很多，具体原因还没找到，后来试着把词性标注去掉，发现性能又恢复正常，猜测这里出了问题，当时事情比较多，另外业务对词性这块没有需求，是对分词结果有要求，就暂时把这个移除了。你如果感兴趣，可以看下我的提交历史， 6954ee65a67146aef022d1de641794dee509d6da 这个提交，可以测试下，如果能帮我找到原因，那最好了。

**Comment by piaolingxue** [comment]
@yanbosan  还有别的问题吗?
