### ISSUE TITLE
自定义添加词典 只支持 完整的词典定义

### ISSUE THREAD

**Issue by jdkcn** [huaban/jieba-analysis#15]
看了一下代码.只有 词, 次频,词性 都有的次才会load.. 可是本身结巴分词是不限制的呢.

**Comment by piaolingxue** [comment]
@jdkcn 你好，目前必须有词、词频才会 load，即使不限制，代码里也会设定默认值，后面也可以用类似方式处理。当前版本你可以自己在用户词后面添加通用词频 3。

**Comment by Jeru2023** [comment]
我希望可以不要指定词典里的词频，像PYTHON一样由jieba自己决定概率，如何可以实现?
