### ISSUE TITLE
关于模型文件prob_emit.txt

### ISSUE THREAD

**Issue by chenjun0210** [huaban/jieba-analysis#30]
这个模型文件怎么训练出来的啊。训练语料用的是？以及对应的训练代码有吗？我这边想更新一下这个模型文件。因为我用的分词器是电商领域。

**Comment by piaolingxue** [comment]
你好 @chenjun0210 ，这个只是 jieba 分词的 java 版本，原作者是 @fxsjy，你可以去作者项目主页找找看 https://github.com/fxsjy/jieba
