### ISSUE TITLE
想问下这java版的jieba能支持多线程同时调用么

### ISSUE THREAD

**Issue by NoneElse** [huaban/jieba-analysis#49]
* 场景是这样，我先```JiebaSegmenter segmenter = new JiebaSegmenter();```，然后再多线程调用```segmenter.process```方法，这样会不会有问题？

**Comment by alexqdjay** [comment]
从源码上看对于公共的资源只有读取没有修改，所以是线程安全的

**Comment by piaolingxue** [comment]
线程安全的
