### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by vector4wang** [huaban/jieba-analysis#73]
我的项目里有使用此开源项目进行分词的功能，总是发现程序在运行很长时间后(半个月以上)，机器的内存老是处于上升的阶段，然后我使用MAT工具分析了下堆转储文件之后，提示如下：
[![截图_20180816173117](https://i.loli.net/2018/08/16/5b75447b1ef11.png)](https://i.loli.net/2018/08/16/5b75447b1ef11.png)

这个该如何优化

**Comment by vector4wang** [comment]
One instance of "com.huaban.analysis.jieba.WordDictionary" loaded by "sun.misc.Launcher$AppClassLoader @ 0x7000015e0" occupies 72,103,344 (58.87%) bytes. The memory is accumulated in one instance of "com.huaban.analysis.jieba.WordDictionary" loaded by "sun.misc.Launcher$AppClassLoader @ 0x7000015e0".

Keywords
sun.misc.Launcher$AppClassLoader @ 0x7000015e0
com.huaban.analysis.jieba.WordDictionary

**Comment by vector4wang** [comment]
[![微信截图_20180816173605.png](https://i.loli.net/2018/08/16/5b75459fc22a3.png)](https://i.loli.net/2018/08/16/5b75459fc22a3.png)

**Comment by jinglongjun** [comment]
麻烦问下最后解决了么？我也有遇到这个情况。

**Comment by vector4wang** [comment]
把那些hashmap改成静态变量试试，我是这么做的

**Comment by weihua04** [comment]
尝试下这个解决方案：https://blog.csdn.net/whatwho_518/article/details/125416242?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125416242%22%2C%22source%22%3A%22whatwho_518%22%7D&ctrtid=hkIGO

**Comment by Tiane-ira** [comment]
里面的对象都是 static 单例引用，所以这个应该不是内存泄漏
![企业微信截图_16687886672475](https://user-images.githubusercontent.com/82498494/202753438-53e3d169-6ab9-4a69-b499-b7bfec74886f.png)
